"""Chat v3 shared constants."""

TOOL_PURPOSES = {
    "query_ontology_data": "按指标、维度和筛选条件查询业务数据。",
    "python_analyze": "当查询结果较大或多结果需要比较时，基于完整查询结果做二次聚合、计算或比较分析。",
    "execute_action": "根据分析结果触发需要确认的业务动作。",
}

FINAL_ANSWER_PROMPT = """你是 ChatBI 的最终答复生成器。

请只基于用户问题、已执行工具结果和模型草稿生成最终答复，不要提出或暗示还需要调用工具。
要求：
1. 用中文回答，表达简洁、自然、业务可读。
2. 优先总结关键结论，再补充必要的数据依据或口径。
3. 如果工具结果包含错误或没有数据，要说明限制，不要编造数值。
4. 不要输出 SQL、JSON、工具参数或内部执行细节，除非用户明确要求。
5. 保留对图表/明细结果有帮助的字段名和指标名。
"""

DEFAULT_TOOL_PURPOSE = "执行当前分析步骤所需的辅助能力。"

DEFAULT_MAX_ROUNDS = 20
MAX_STATE_TRANSITIONS = 50

LLM_TOOL_CALL_TEMPERATURE = 0.5
LLM_TOOL_CALL_MAX_TOKENS = 2048
FINAL_ANSWER_TEMPERATURE = 0.3
FINAL_ANSWER_MAX_TOKENS = 1600

MAX_FINAL_TOOL_CONTEXT_CHARS = 12000
MAX_FINAL_DRAFT_CHARS = 6000
TOOL_ARGUMENT_LOG_MAX_CHARS = 1000
TOOL_RESULT_PREVIEW_MAX_CHARS = 3000
DIRECT_FINAL_RESULT_MAX_ROWS = 100
JSON_SAFE_PREVIEW_ROWS = 100
CONVERSATION_MESSAGE_ID_SUFFIX_LENGTH = 12

SCHEMA_CLASS_PROPERTY_PREVIEW_LIMIT = 10

CONTEXT_COMPRESSOR_HARD_LIMIT = 20000
CONTEXT_COMPRESSOR_HEAD_RATIO = 0.75
CONTEXT_COMPRESSOR_TAIL_RATIO = 0.25

ENTITY_MATCH_THRESHOLD = 0.75
ENTITY_HINT_CANDIDATE_LIMIT = 5
ENTITY_FIELD_VALUE_SEARCH_LIMIT = 30
ENTITY_MENTION_LIMIT = 12
ENTITY_CN_VARIANT_MAX_WINDOW = 6
ENTITY_CORE_EXACT_SCORE = 0.95
ENTITY_CORE_CONTAINS_SCORE = 0.85
ENTITY_CANDIDATE_CONTAINS_SCORE = 0.80

TOOL_EXECUTOR_MAX_RETRY = 1
TOOL_AUTOCORRECT_LOG_MAX_CHARS = 1000
TEXT_FILTER_VALUE_SEARCH_LIMIT = 20
AUTOCORRECT_VALUE_SEARCH_LIMIT = 50